inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false

  Exclude:
    - "spec/dummy/bin/*"

Style:
  HashSyntax:
    EnforcedStyle: hash_rockets

  GuardClause:
    Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "lib/generators/seedie/install_generator.rb"

# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
# AllowedMethods: refine
Metrics/BlockLength:
  CountComments: false
  Max: 30
  Exclude: 
    - "spec/integration/*.rb"
    - "spec/seedie/**/*.rb"
    - "spec/generators/*.rb"
    - "spec/dummy/**/*.rb"

