inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false

  Exclude:
    - "spec/dummy/bin/*"

Style:
  HashSyntax:
    EnforcedStyle: hash_rockets

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "lib/generators/seedie/install_generator.rb"
