name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Build and test with Rake
      env:
        RAILS_ENV: test
      run: |
        sudo apt-get -qq install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake db:create db:schema:load
        bundle exec rake
